### PR TITLE
ImageClickListener

### PR DESCRIPTION
**Pull request by leonardo2204**
Added Click support to the image.
Should be useful if using inside a RecyclerView to pass touch events ahead (like opening a new activity).

PS. If you choose to accept it, please, let me know before so I can add some Doc in the Readme !

### CODE REVIEW

**Comment by sayyam** [comment]
@leonardo2204 you can update the documentation.

**Comment by leonardo2204** [comment]
@sayyam Done !

**Comment by leonardo2204** [comment]
Is this ever going live ?

**Comment by RazmigPapissian** [comment]
Hey guys! Is there's an ETA on merge for the Click support?

**Comment by sayyam** [comment]
Done.
you can get an update on v0.1.2

Thanks for your contribution @leonardo2204 .

**Comment by RazmigPapissian** [comment]
@sayyam @leonardo2204  Thanks guys!

**Pull request merged**
